package com.xworkz.collectionMethods.boot;

import java.util.Collection;
import java.util.TreeSet;

public class Mall {
	public static void main(String[] args) {
		String mall1 = "World Trade Park Mall";
		String mall2 = "Phoenix Marketcity Mall";
		String mall3 = "Elante Mall";
		String mall4 = "Esplanade One Mall";
		String mall5 = "Phoenix Marketcity Mall";
		String mall6 = "Mantri Square Mall";
		String mall7 = "Orion Mall";
		String mall8 = "Ambience Mall";
		String mall9 = "Lulu Mall";
		String mall10 = "DLF Mall of India";
		String mall11 = "R City Mall";
		String mall12 = "Elante Mall";
		String mall13 = "Magneto the mall";
		String mall14 = "The Great India Place";
		String mall15 = "South City Mall";
		String mall16 = "Z Square Mall";
		String mall17 = "Express Avenue";
		String mall18 = "Phoenix Palassio";
		String mall19 = "Nexus Sujana Mall";
		String mall20 = "Acropolis Mall";
		String mall21 = "Growel's 101";
		String mall22 = "Quest Mall";
		String mall23 = "Nexus Fiza Mall";
		String mall24 = "The Nexus Vijaya";
		String mall25 = "Vegas Mall";
		String mall26 = "VR Surat";
		String mall27 = "Select Citywalk";
		String mall28 = "Royal Meenakshi Mall";
		String mall29 = "Moments Mall";
		String mall30 = "Bhawani Mall";
		String mall31 = "Avani Riverside Mall";
		String mall32 = "World Square Mall";
		String mall33 = "VR Bengaluru";
		String mall34 = "Logix City Centre";
		String mall35 = "Metro Junction Mall";
		String mall36 = "Spencer Plaza";
		String mall37 = "Axis Mall";
		String mall38 = "MSX Mall";
		String mall39 = "Texvalley";
		String mall40 = "Lodha Xperia Mall";

		Collection<String> collection = new TreeSet();
		collection.add(mall1);
		collection.add(mall2);
		collection.add(mall3);
		collection.add(mall4);
		collection.add(mall5);
		collection.add(mall6);
		collection.add(mall7);
		collection.add(mall8);
		collection.add(mall9);
		collection.add(mall10);
		collection.add(mall11);
		collection.add(mall12);
		collection.add(mall13);
		collection.add(mall14);
		collection.add(mall15);
		collection.add(mall16);
		collection.add(mall17);
		collection.add(mall18);
		collection.add(mall19);
		collection.add(mall20);
		collection.add(mall21);
		collection.add(mall22);
		collection.add(mall23);
		collection.add(mall24);
		collection.add(mall25);
		collection.add(mall26);
		collection.add(mall27);
		collection.add(mall28);
		collection.add(mall29);
		collection.add(mall30);
		collection.add(mall31);
		collection.add(mall32);
		collection.add(mall33);
		collection.add(mall34);
		collection.add(mall35);
		collection.add(mall36);
		collection.add(mall37);
		collection.add(mall38);
		collection.add(mall39);
		collection.add(mall40);
		System.out.println(collection.size());
		collection.clear();
		System.out.println(collection.size());
	}
}
